import { AfterContentInit, OnInit, QueryList } from "@angular/core";
import { ChartTitleComponent } from "../charttitle/chart.title.component";
import { ChartLegendComponent } from "../chartlegend/chart.legend.component";
import { ChartAreaComponent } from "../chartarea/chart.area.component";
export declare class PieChartComponent implements AfterContentInit, OnInit {
    private options;
    private pieData;
    private chart;
    id: any;
    width: string;
    height: string;
    is3D: boolean;
    pieHole: number;
    data: any;
    pieStartAngle: number;
    backgroundColor: string;
    chartLegendComp: QueryList<ChartLegendComponent>;
    chartTitleComp: QueryList<ChartTitleComponent>;
    chartAreaComp: QueryList<ChartAreaComponent>;
    chartAreaArray: ChartAreaComponent[];
    chartAreaComponent: ChartAreaComponent;
    chartLegendArray: ChartLegendComponent[];
    chartLengendComponent: ChartLegendComponent;
    chartTitleArray: ChartTitleComponent[];
    chartTitleComponent: ChartTitleComponent;
    constructor();
    drawChart(): void;
    onClick(e: any): void;
    ngAfterContentInit(): void;
    ngOnInit(): void;
}
